### ISSUE TITLE
Election Vote Counting

### ISSUE THREAD

**Issue by UnsignedByte** [UnsignedByte/Democracy-Bot#13]
Count votes for elections! only upvotes for reps are counted.

Auto-give roles afterwards

**Comment by Nichodon** [comment]
1. Add run requests
2. Display all candidates
3. Votes not publicized, only counts shown:

@everyone **LEADER ELECTION**
Candidate :regional_indicator_a: I will be a leader
:thumbsup: 1 | :thumbsdown: 100000000

**Comment by Nichodon** [comment]
Done
