### ISSUE TITLE
Proposals

### ISSUE THREAD

**Issue by Nichodon** [UnsignedByte/Democracy-Bot#2]
Proposals are put into 
```python
server_data[server.id]["proposals"]["messages"]
```
as a list and can be accessed using the `nested_get()` function

Upon reaction_add or reaction_delete, demobot should check if the 👍 or the 👎 emojis are being added to a proposal by a representative. If it is not by a rep, but is on a proposal, the user will be imprisoned and the reaction removed. If a proposal passes, the ✅ should be added to rule, amendment, and override props and rules made in #rules, etc. For mod proposals add ✔️ and mention an enforcer in a specified channel (maybe #enforcer_todo or something). When a rep that voted up on the proposal acknowledges that the enforcer has performed the action, the ✔️ should be switched with a ✅

**Comment by UnsignedByte** [comment]
Non command based!

**Comment by UnsignedByte** [comment]
Also we have to make amendment proposals diff from other props
